-- author: Joseph Park
-- NOT SUPPORTED: autogenerated from careplan_getitemvalues.Rmd by using show_query()

DROP MATERIALIZED VIEW IF EXISTS possibleCodeStatus;
CREATE MATERIALIZED VIEW possibleCodeStatus AS

SELECT "cplitemvalue", count(*) AS "n"
FROM "careplangeneral"
GROUP BY "cplitemvalue"
ORDER BY "n" DESC;