-- -------------------------------------------------------------------------------
--
-- Create the eICU tables
--
-- -------------------------------------------------------------------------------

-- NOTE: unless specified here or when calling this script via psql, all tables
-- will be created on the public schema. To redefine the search path, call:
--    SET search_path TO schema_name_you_want;
-- Restoring the search path to its default value can be accomplished as follows:
--    SET search_path TO "$user",public;

--------------------------------------------------------
--  DDL for Table ADMISSIONDX
--------------------------------------------------------

DROP TABLE IF EXISTS ADMISSIONDX CASCADE;
CREATE TABLE ADMISSIONDX
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
  ADMISSIONDXID BIGINT NOT NULL,
  ADMITDXENTEREDYEAR SMALLINT NOT NULL,
  ADMITDXENTEREDTIME24 VARCHAR(8) NOT NULL,
  ADMITDXENTEREDTIME VARCHAR(20) NOT NULL,
  ADMITDXENTEREDOFFSET BIGINT NOT NULL,
  ADMITDXPATH VARCHAR(500) NOT NULL,
  ADMITDXNAME VARCHAR(255),
  ADMITDXTEXT VARCHAR(255)
) ;
--------------------------------------------------------
--  DDL for Table APACHEAPSVAR
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEAPSVAR CASCADE;
CREATE TABLE APACHEAPSVAR
(
	PATIENTUNITSTAYID BIGINT,
	APACHEAPSVARID BIGINT,
	INTUBATED BIGINT,
	VENT BIGINT,
	DIALYSIS BIGINT,
	EYES BIGINT,
	MOTOR BIGINT,
	VERBAL BIGINT,
	MEDS BIGINT,
	URINE DOUBLE PRECISION,
	WBC DOUBLE PRECISION,
	TEMPERATURE DOUBLE PRECISION,
	RESPIRATORYRATE DOUBLE PRECISION,
	SODIUM DOUBLE PRECISION,
	HEARTRATE DOUBLE PRECISION,
	MEANBP DOUBLE PRECISION,
	PH DOUBLE PRECISION,
	HEMATOCRIT DOUBLE PRECISION,
	CREATININE DOUBLE PRECISION,
	ALBUMIN DOUBLE PRECISION,
	PAO2 DOUBLE PRECISION,
	PCO2 DOUBLE PRECISION,
	BUN DOUBLE PRECISION,
	GLUCOSE DOUBLE PRECISION,
	BILIRUBIN DOUBLE PRECISION,
	FIO2 DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table APACHEPATIENTRESULTS
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEPATIENTRESULT CASCADE;
CREATE TABLE APACHEPATIENTRESULT
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	APACHEPATIENTRESULTSID BIGINT NOT NULL,
	PHYSICIANSPECIALITY VARCHAR(50),
	PHYSICIANINTERVENTIONCATEGORY VARCHAR(50),
	ACUTEPHYSIOLOGYSCORE BIGINT,
	APACHESCORE BIGINT,
	APACHEVERSION VARCHAR(5) NOT NULL,
	PREDICTEDICUMORTALITY VARCHAR(50),
	ACTUALICUMORTALITY VARCHAR(50),
	PREDICTEDICULOS DOUBLE PRECISION,
	ACTUALICULOS DOUBLE PRECISION,
	PREDICTEDHOSPITALMORTALITY VARCHAR(50),
	ACTUALHOSPITALMORTALITY VARCHAR(50),
	PREDICTEDHOSPITALLOS DOUBLE PRECISION,
	ACTUALHOSPITALLOS DOUBLE PRECISION,
	PREOPMI BIGINT,
	PREOPCARDIACCATH BIGINT,
	PTCAWITHIN24H BIGINT,
	UNABRIDGEDUNITLOS DOUBLE PRECISION,
	UNABRIDGEDHOSPLOS DOUBLE PRECISION,
	ACTUALVENTDAYS DOUBLE PRECISION,
	PREDVENTDAYS DOUBLE PRECISION,
	UNABRIDGEDACTUALVENTDAYS DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table APACHEPREDVAR
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEPREDVAR CASCADE;
CREATE TABLE APACHEPREDVAR
(
	PATIENTUNITSTAYID BIGINT,
	APACHEPREDVARID BIGINT,
	SICUDAY BIGINT,
	SAPS3DAY1 BIGINT,
	SAPS3TODAY BIGINT,
	SAPS3YESTERDAY BIGINT,
	GENDER BIGINT,
	TEACHTYPE BIGINT,
	REGION BIGINT,
	BEDCOUNT BIGINT,
	ADMITSOURCE BIGINT,
	GRAFTCOUNT BIGINT,
	MEDS BIGINT,
	VERBAL BIGINT,
	MOTOR BIGINT,
	EYES BIGINT,
	AGE BIGINT,
	ADMITDIAGNOSIS VARCHAR(11),
	THROMBOLYTICS BIGINT,
	DIEDINHOSPITAL BIGINT,
	AIDS BIGINT,
	HEPATICFAILURE BIGINT,
	LYMPHOMA BIGINT,
	METASTATICCANCER BIGINT,
	LEUKEMIA BIGINT,
	IMMUNOSUPPRESSION BIGINT,
	CIRRHOSIS BIGINT,
	ELECTIVESURGERY BIGINT,
	ACTIVETX BIGINT,
	READMIT BIGINT,
	IMA BIGINT,
	MIDUR BIGINT,
	VENTDAY1 BIGINT,
	OOBVENTDAY1 BIGINT,
	OOBINTUBDAY1 BIGINT,
	DIABETES BIGINT,
	MANAGEMENTSYSTEM BIGINT,
	VAR03HSPXLOS DOUBLE PRECISION,
	PAO2 DOUBLE PRECISION,
	FIO2 DOUBLE PRECISION,
	EJECTFX DOUBLE PRECISION,
	CREATININE DOUBLE PRECISION,
	DISCHARGELOCATION BIGINT,
	VISITNUMBER BIGINT,
	AMILOCATION BIGINT,
	DAY1MEDS BIGINT,
	DAY1VERBAL BIGINT,
	DAY1MOTOR BIGINT,
	DAY1EYES BIGINT,
	DAY1PAO2 DOUBLE PRECISION,
	DAY1FIO2 DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

DROP TABLE IF EXISTS PATIENT CASCADE;
CREATE TABLE PATIENT
(
	PATIENTUNITSTAYID BIGINT,
	PATIENTHEALTHSYSTEMSTAYID BIGINT,
	GENDER VARCHAR(25),
	AGE VARCHAR(10),
	ETHNICITY VARCHAR(50),
	HOSPITALID BIGINT,
	WARDID BIGINT,
	APACHEADMISSIONDX VARCHAR(1000),
	ADMISSIONHEIGHT DECIMAL(10,2),
	HOSPITALADMITYEAR SMALLINT,
	HOSPITALADMITTIME24 VARCHAR(8),
	HOSPITALADMITTIME VARCHAR(20),
	HOSPITALADMITOFFSET BIGINT,
	HOSPITALADMITSOURCE VARCHAR(30),
	HOSPITALDISCHARGEYEAR SMALLINT,
	HOSPITALDISCHARGETIME24 VARCHAR(8),
	HOSPITALDISCHARGETIME VARCHAR(20),
	HOSPITALDISCHARGEOFFSET BIGINT,
	HOSPITALDISCHARGELOCATION VARCHAR(100),
	HOSPITALDISCHARGESTATUS VARCHAR(10),
	UNITTYPE VARCHAR(50),
	UNITADMITYEAR SMALLINT,
	UNITADMITTIME24 VARCHAR(8),
	UNITADMITTIME VARCHAR(20),
	UNITADMITSOURCE VARCHAR(100),
	UNITVISITNUMBER BIGINT,
	UNITSTAYTYPE VARCHAR(15),
	ADMISSIONWEIGHT DECIMAL(10,2),
	DISCHARGEWEIGHT DECIMAL(10,2),
	UNITDISCHARGEYEAR SMALLINT,
	UNITDISCHARGETIME24 VARCHAR(8),
	UNITDISCHARGETIME VARCHAR(20),
	UNITDISCHARGEOFFSET BIGINT,
	UNITDISCHARGELOCATION VARCHAR(100),
	UNITDISCHARGESTATUS VARCHAR(10),
	AUDITETLRUNID CHAR(40),
	UNIQUEPID VARCHAR(10)
) ;
