-- -------------------------------------------------------------------------------
--
-- Create the eICU tables
--
-- -------------------------------------------------------------------------------

-- NOTE: unless specified here or when calling this script via psql, all tables
-- will be created on the public schema. To redefine the search path, call:
--    SET search_path TO schema_name_you_want;
-- Restoring the search path to its default value can be accomplished as follows:
--    SET search_path TO "$user",public;

--------------------------------------------------------
--  DDL for Table ADMISSIONDX
--------------------------------------------------------

DROP TABLE IF EXISTS ADMISSIONDX CASCADE;
CREATE TABLE ADMISSIONDX
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
  ADMISSIONDXID BIGINT NOT NULL,
  ADMITDXENTEREDYEAR SMALLINT NOT NULL,
  ADMITDXENTEREDTIME24 VARCHAR(8) NOT NULL,
  ADMITDXENTEREDTIME VARCHAR(20) NOT NULL,
  ADMITDXENTEREDOFFSET BIGINT NOT NULL,
  ADMITDXPATH VARCHAR(500) NOT NULL,
  ADMITDXNAME VARCHAR(255),
  ADMITDXTEXT VARCHAR(255)
) ;
--------------------------------------------------------
--  DDL for Table APACHEAPSVAR
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEAPSVAR CASCADE;
CREATE TABLE APACHEAPSVAR
(
	PATIENTUNITSTAYID BIGINT,
	APACHEAPSVARID BIGINT,
	INTUBATED BIGINT,
	VENT BIGINT,
	DIALYSIS BIGINT,
	EYES BIGINT,
	MOTOR BIGINT,
	VERBAL BIGINT,
	MEDS BIGINT,
	URINE DOUBLE PRECISION,
	WBC DOUBLE PRECISION,
	TEMPERATURE DOUBLE PRECISION,
	RESPIRATORYRATE DOUBLE PRECISION,
	SODIUM DOUBLE PRECISION,
	HEARTRATE DOUBLE PRECISION,
	MEANBP DOUBLE PRECISION,
	PH DOUBLE PRECISION,
	HEMATOCRIT DOUBLE PRECISION,
	CREATININE DOUBLE PRECISION,
	ALBUMIN DOUBLE PRECISION,
	PAO2 DOUBLE PRECISION,
	PCO2 DOUBLE PRECISION,
	BUN DOUBLE PRECISION,
	GLUCOSE DOUBLE PRECISION,
	BILIRUBIN DOUBLE PRECISION,
	FIO2 DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table APACHEPATIENTRESULTS
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEPATIENTRESULT CASCADE;
CREATE TABLE APACHEPATIENTRESULT
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	APACHEPATIENTRESULTSID BIGINT NOT NULL,
	PHYSICIANSPECIALITY VARCHAR(50),
	PHYSICIANINTERVENTIONCATEGORY VARCHAR(50),
	ACUTEPHYSIOLOGYSCORE BIGINT,
	APACHESCORE BIGINT,
	APACHEVERSION VARCHAR(5) NOT NULL,
	PREDICTEDICUMORTALITY VARCHAR(50),
	ACTUALICUMORTALITY VARCHAR(50),
	PREDICTEDICULOS DOUBLE PRECISION,
	ACTUALICULOS DOUBLE PRECISION,
	PREDICTEDHOSPITALMORTALITY VARCHAR(50),
	ACTUALHOSPITALMORTALITY VARCHAR(50),
	PREDICTEDHOSPITALLOS DOUBLE PRECISION,
	ACTUALHOSPITALLOS DOUBLE PRECISION,
	PREOPMI BIGINT,
	PREOPCARDIACCATH BIGINT,
	PTCAWITHIN24H BIGINT,
	UNABRIDGEDUNITLOS DOUBLE PRECISION,
	UNABRIDGEDHOSPLOS DOUBLE PRECISION,
	ACTUALVENTDAYS DOUBLE PRECISION,
	PREDVENTDAYS DOUBLE PRECISION,
	UNABRIDGEDACTUALVENTDAYS DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table APACHEPREDVAR
--------------------------------------------------------

DROP TABLE IF EXISTS APACHEPREDVAR CASCADE;
CREATE TABLE APACHEPREDVAR
(
	PATIENTUNITSTAYID BIGINT,
	APACHEPREDVARID BIGINT,
	SICUDAY BIGINT,
	SAPS3DAY1 BIGINT,
	SAPS3TODAY BIGINT,
	SAPS3YESTERDAY BIGINT,
	GENDER BIGINT,
	TEACHTYPE BIGINT,
	REGION BIGINT,
	BEDCOUNT BIGINT,
	ADMITSOURCE BIGINT,
	GRAFTCOUNT BIGINT,
	MEDS BIGINT,
	VERBAL BIGINT,
	MOTOR BIGINT,
	EYES BIGINT,
	AGE BIGINT,
	ADMITDIAGNOSIS VARCHAR(11),
	THROMBOLYTICS BIGINT,
	DIEDINHOSPITAL BIGINT,
	AIDS BIGINT,
	HEPATICFAILURE BIGINT,
	LYMPHOMA BIGINT,
	METASTATICCANCER BIGINT,
	LEUKEMIA BIGINT,
	IMMUNOSUPPRESSION BIGINT,
	CIRRHOSIS BIGINT,
	ELECTIVESURGERY BIGINT,
	ACTIVETX BIGINT,
	READMIT BIGINT,
	IMA BIGINT,
	MIDUR BIGINT,
	VENTDAY1 BIGINT,
	OOBVENTDAY1 BIGINT,
	OOBINTUBDAY1 BIGINT,
	DIABETES BIGINT,
	MANAGEMENTSYSTEM BIGINT,
	VAR03HSPXLOS DOUBLE PRECISION,
	PAO2 DOUBLE PRECISION,
	FIO2 DOUBLE PRECISION,
	EJECTFX DOUBLE PRECISION,
	CREATININE DOUBLE PRECISION,
	DISCHARGELOCATION BIGINT,
	VISITNUMBER BIGINT,
	AMILOCATION BIGINT,
	DAY1MEDS BIGINT,
	DAY1VERBAL BIGINT,
	DAY1MOTOR BIGINT,
	DAY1EYES BIGINT,
	DAY1PAO2 DOUBLE PRECISION,
	DAY1FIO2 DOUBLE PRECISION
) ;

--------------------------------------------------------
--  DDL for Table CAREPLANCAREPROVIDER
--------------------------------------------------------

DROP TABLE IF EXISTS CAREPLANCAREPROVIDER CASCADE;
CREATE TABLE CAREPLANCAREPROVIDER
(
	CPLCAREPROVDERID BIGINT NOT NULL,
	PATIENTUNITSTAYID BIGINT NOT NULL,
	CAREPROVIDERSAVEYEAR SMALLINT NOT NULL,
	CAREPROVIDERSAVETIME24 VARCHAR(8) NOT NULL,
	CAREPROVIDERSAVETIME VARCHAR(20) NOT NULL,
	CAREPROVIDERSAVEOFFSET BIGINT NOT NULL,
	PROVIDERTYPE VARCHAR(255),
	SPECIALTY VARCHAR(255),
	INTERVENTIONCATEGORY VARCHAR(255),
	MANAGINGPHYSICIAN VARCHAR(50),
	ACTIVEUPONDISCHARGE VARCHAR(10) NOT NULL
) ;
--------------------------------------------------------
--  DDL for Table CAREPLANEOL
--------------------------------------------------------

DROP TABLE IF EXISTS CAREPLANEOL CASCADE;
CREATE TABLE CAREPLANEOL
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	CPLEOLID BIGINT NOT NULL,
	CPLEOLSAVEYEAR SMALLINT NOT NULL,
	CPLEOLSAVETIME24 VARCHAR(8) NOT NULL,
	CPLEOLSAVETIME VARCHAR(20) NOT NULL,
	CPLEOLSAVEOFFSET BIGINT NOT NULL,
	CPLEOLDISCUSSIONYEAR SMALLINT,
	CPLEOLDISCUSSIONTIME24 VARCHAR(8),
	CPLEOLDISCUSSIONTIME VARCHAR(20),
	CPLEOLDISCUSSIONOFFSET BIGINT,
	ACTIVEUPONDISCHARGE VARCHAR(10)
) ;
--------------------------------------------------------
--  DDL for Table CAREPLANGENERAL
--------------------------------------------------------

DROP TABLE IF EXISTS CAREPLANGENERAL CASCADE;
CREATE TABLE CAREPLANGENERAL
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	ACTIVEUPONDISCHARGE VARCHAR(10) NOT NULL,
	CPLGENERALID BIGINT NOT NULL,
	CPLITEMYEAR SMALLINT NOT NULL,
	CPLITEMTIME24 VARCHAR(8) NOT NULL,
	CPLITEMTIME VARCHAR(20) NOT NULL,
	CPLITEMOFFSET BIGINT NOT NULL,
	CPLGROUP VARCHAR(255) NOT NULL,
	CPLITEMVALUE VARCHAR(1024)
) ;
--------------------------------------------------------
--  DDL for Table CAREPLANGOAL
--------------------------------------------------------

DROP TABLE IF EXISTS CAREPLANGOAL CASCADE;
CREATE TABLE CAREPLANGOAL
(
	CPLGOALID BIGINT NOT NULL,
	PATIENTUNITSTAYID BIGINT NOT NULL,
	CPLGOALYEAR SMALLINT NOT NULL,
	CPLGOALTIME24 VARCHAR(8) NOT NULL,
	CPLGOALTIME VARCHAR(20) NOT NULL,
	CPLGOALOFFSET BIGINT NOT NULL,
	CPLGOALCATEGORY VARCHAR(255),
	CPLGOALVALUE VARCHAR(1000),
	CPLGOALSTATUS VARCHAR(255),
	ACTIVEUPONDISCHARGE VARCHAR(10) NOT NULL
) ;
--------------------------------------------------------
--  DDL for Table CAREPLANINFECTIOUSDISEASE
--------------------------------------------------------

DROP TABLE IF EXISTS CAREPLANINFECTIOUSDISEASE CASCADE;
CREATE TABLE CAREPLANINFECTIOUSDISEASE
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	ACTIVEUPONDISCHARGE VARCHAR(10) NOT NULL,
	CPLINFECTID BIGINT NOT NULL,
	CPLINFECTDISEASEYEAR SMALLINT NOT NULL,
	CPLINFECTDISEASETIME24 VARCHAR(8) NOT NULL,
	CPLINFECTDISEASETIME VARCHAR(20) NOT NULL,
	CPLINFECTDISEASEOFFSET BIGINT NOT NULL,
	INFECTDISEASESITE VARCHAR(64),
	INFECTDISEASEASSESSMENT VARCHAR(64),
	RESPONSETOTHERAPY VARCHAR(32),
	TREATMENT VARCHAR(32)
) ;
--------------------------------------------------------
--  DDL for Table DIAGNOSIS
--------------------------------------------------------

DROP TABLE IF EXISTS DIAGNOSIS CASCADE;
CREATE TABLE DIAGNOSIS
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	ACTIVEUPONDISCHARGE VARCHAR(64),
	DIAGNOSISID BIGINT NOT NULL,
	DIAGNOSISYEAR SMALLINT NOT NULL,
	DIAGNOSISTIME24 VARCHAR(8) NOT NULL,
	DIAGNOSISTIME VARCHAR(20) NOT NULL,
	DIAGNOSISOFFSET BIGINT NOT NULL,
	DIAGNOSISSTRING VARCHAR(200) NOT NULL,
	ICD9CODE VARCHAR(100),
	DIAGNOSISPRIORITY VARCHAR(10) NOT NULL
) ;
--------------------------------------------------------
--  DDL for Table HOSPITAL
--------------------------------------------------------

DROP TABLE IF EXISTS HOSPITAL CASCADE;
CREATE TABLE HOSPITAL
(
	HOSPITALID INT NOT NULL,
	NUMBEDSCATEGORY VARCHAR(32),
	TEACHINGSTATUS BOOLEAN,
	REGION VARCHAR(64)
) ;
--------------------------------------------------------
--  DDL for Table LAB
--------------------------------------------------------

DROP TABLE IF EXISTS LAB CASCADE;
CREATE TABLE LAB
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	LABID BIGINT NOT NULL,
	LABRESULTYEAR SMALLINT NOT NULL,
	LABRESULTTIME24 VARCHAR(8) NOT NULL,
	LABRESULTTIME VARCHAR(20) NOT NULL,
	LABRESULTOFFSET BIGINT NOT NULL,
	LABTYPEID DECIMAL(3,0) NOT NULL,
	LABNAME VARCHAR(256),
	LABRESULT DECIMAL(11,4),
	LABRESULTTEXT VARCHAR(255),
	LABMEASURENAMESYSTEM VARCHAR(255),
	LABMEASURENAMEINTERFACE VARCHAR(255),
	LABRESULTREVISEDYEAR SMALLINT,
	LABRESULTREVISEDTIME24 VARCHAR(8),
	LABRESULTREVISEDTIME VARCHAR(20),
	LABRESULTREVISEDOFFSET BIGINT
) ;
--------------------------------------------------------
--  DDL for Table PASTHISTORY
--------------------------------------------------------

DROP TABLE IF EXISTS PASTHISTORY CASCADE;
CREATE TABLE PASTHISTORY
(
	PASTHISTORYID BIGINT NOT NULL,
	PATIENTUNITSTAYID BIGINT NOT NULL,
	PASTHISTORYYEAR SMALLINT NOT NULL,
	PASTHISTORYTIME24 VARCHAR(8) NOT NULL,
	PASTHISTORYTIME VARCHAR(20) NOT NULL,
	PASTHISTORYOFFSET BIGINT NOT NULL,
	PASTHISTORYENTEREDYEAR SMALLINT NOT NULL,
	PASTHISTORYENTEREDTIME24 VARCHAR(8) NOT NULL,
	PASTHISTORYENTEREDTIME VARCHAR(20) NOT NULL,
	PASTHISTORYENTEREDOFFSET BIGINT NOT NULL,
	PASTHISTORYNOTETYPE VARCHAR(40),
	PASTHISTORYPATH VARCHAR(255) NOT NULL,
	PASTHISTORYVALUE VARCHAR(100),
	PASTHISTORYVALUETEXT VARCHAR(255)
) ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

DROP TABLE IF EXISTS PATIENT CASCADE;
CREATE TABLE PATIENT
(
	PATIENTUNITSTAYID BIGINT,
	PATIENTHEALTHSYSTEMSTAYID BIGINT,
	GENDER VARCHAR(25),
	AGE VARCHAR(10),
	ETHNICITY VARCHAR(50),
	HOSPITALID BIGINT,
	WARDID BIGINT,
	APACHEADMISSIONDX VARCHAR(1000),
	ADMISSIONHEIGHT DECIMAL(10,2),
	HOSPITALADMITYEAR SMALLINT,
	HOSPITALADMITTIME24 VARCHAR(8),
	HOSPITALADMITTIME VARCHAR(20),
	HOSPITALADMITOFFSET BIGINT,
	HOSPITALADMITSOURCE VARCHAR(30),
	HOSPITALDISCHARGEYEAR SMALLINT,
	HOSPITALDISCHARGETIME24 VARCHAR(8),
	HOSPITALDISCHARGETIME VARCHAR(20),
	HOSPITALDISCHARGEOFFSET BIGINT,
	HOSPITALDISCHARGELOCATION VARCHAR(100),
	HOSPITALDISCHARGESTATUS VARCHAR(10),
	UNITTYPE VARCHAR(50),
	UNITADMITYEAR SMALLINT,
	UNITADMITTIME24 VARCHAR(8),
	UNITADMITTIME VARCHAR(20),
	UNITADMITSOURCE VARCHAR(100),
	UNITVISITNUMBER BIGINT,
	UNITSTAYTYPE VARCHAR(15),
	ADMISSIONWEIGHT DECIMAL(10,2),
	DISCHARGEWEIGHT DECIMAL(10,2),
	UNITDISCHARGEYEAR SMALLINT,
	UNITDISCHARGETIME24 VARCHAR(8),
	UNITDISCHARGETIME VARCHAR(20),
	UNITDISCHARGEOFFSET BIGINT,
	UNITDISCHARGELOCATION VARCHAR(100),
	UNITDISCHARGESTATUS VARCHAR(10),
	AUDITETLRUNID CHAR(40),
	UNIQUEPID VARCHAR(10)
) ;
--------------------------------------------------------
--  DDL for Table TREATMENT
--------------------------------------------------------

DROP TABLE IF EXISTS TREATMENT CASCADE;
CREATE TABLE TREATMENT
(
	PATIENTUNITSTAYID BIGINT,
	TREATMENTID BIGINT,
	TREATMENTYEAR SMALLINT,
	TREATMENTTIME24 VARCHAR(8),
	TREATMENTTIME VARCHAR(20),
	TREATMENTOFFSET BIGINT,
	TREATMENTSTRING VARCHAR(200),
	ACTIVEUPONDISCHARGE VARCHAR(10)
) ;
--------------------------------------------------------
--  DDL for Table VITALAPERIODIC
--------------------------------------------------------

DROP TABLE IF EXISTS VITALAPERIODIC CASCADE;
CREATE TABLE VITALAPERIODIC
(
	PATIENTUNITSTAYID BIGINT NOT NULL,
	VITALAPERIODICID BIGINT NOT NULL,
	OBSERVATIONYEAR SMALLINT NOT NULL,
	OBSERVATIONTIME24 VARCHAR(8) NOT NULL,
	OBSERVATIONTIME VARCHAR(20) NOT NULL,
	OBSERVATIONOFFSET BIGINT NOT NULL,
	NONINVASIVESYSTOLIC DOUBLE PRECISION,
	NONINVASIVEDIASTOLIC DOUBLE PRECISION,
	NONINVASIVEMEAN DOUBLE PRECISION,
	PAOP DOUBLE PRECISION,
	CARDIACOUTPUT DOUBLE PRECISION,
	CARDIACINPUT DOUBLE PRECISION,
	SVR DOUBLE PRECISION,
	SVRI DOUBLE PRECISION,
	PVR DOUBLE PRECISION,
	PVRI DOUBLE PRECISION
) ;
--------------------------------------------------------
--  DDL for Table VITALPERIODIC
--------------------------------------------------------

DROP TABLE IF EXISTS VITALPERIODIC CASCADE;
CREATE TABLE VITALPERIODIC
(
	PATIENTUNITSTAYID BIGINT,
	VITALPERIODICID BIGINT,
	OBSERVATIONYEAR SMALLINT,
	OBSERVATIONTIME24 VARCHAR(8),
	OBSERVATIONTIME VARCHAR(20),
	OBSERVATIONOFFSET BIGINT,
	TEMPERATURE DECIMAL(11,4),
	SAO2 BIGINT,
	HEARTRATE BIGINT,
	RESPIRATION BIGINT,
	CVP BIGINT,
	ETCO2 BIGINT,
	SYSTEMICSYSTOLIC BIGINT,
	SYSTEMICDIASTOLIC BIGINT,
	SYSTEMICMEAN BIGINT,
	PASYSTOLIC BIGINT,
	PADIASTOLIC BIGINT,
	PAMEAN BIGINT,
	ST1 DOUBLE PRECISION,
	ST2 DOUBLE PRECISION,
	ST3 DOUBLE PRECISION,
	ICP BIGINT
) ;
